# Generated by Django 3.2.23 on 2023-11-14 17:51

from django.db import migrations

def create_base_tokens(apps, schema_editor):
    Token = apps.get_model('wallet', 'Token')
    Token.objects.create(name="bitcoin", symbol="BTC", actual_price=35000)
    Token.objects.create(name="ethereum", symbol="ETH", actual_price=2500)
    Token.objects.create(name="tether", symbol="USDT", actual_price=1)


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_owner_alter_wallet_token'),
    ]

    operations = [
        migrations.RunPython(create_base_tokens),
    ]
