name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        cd Exchange
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd Exchange
        python manage.py test
      env:
        DATABASE_NAME: testdb
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: ""
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: Exchange
        push: true
        # List of tags
        tags: "latest,${{ github.ref_name }}-latest,${{ github.ref_name }}-${{ github.sha }}"
              
        
