name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_IMAGE_TAGS: "${{ vars.DOCKER_REGISTRY }}/backend/panel:latest,${{ vars.DOCKER_REGISTRY }}/backend/panel:${{ github.ref_name }}-latest,${{ vars.DOCKER_REGISTRY }}/backend/panel:${{ github.ref_name }}-${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: ""
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: Exchange
        outputs: type=docker,dest=/tmp/backend-panel.tar
        tags: ${{ env.DOCKER_IMAGE_TAGS }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-panel
        path: /tmp/backend-panel.tar
        retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-panel
          path: /tmp
      - name: Load Docker image
        run: docker load -i /tmp/backend-panel.tar
      - name: Run tests
        run: |
          docker run --rm \
            -e DATABASE_HOST=postgres \
            -e DATABASE_PORT=5432 \
            -e DATABASE_NAME=testdb \
            -e DATABASE_USER=postgres \
            -e DATABASE_PASSWORD=postgres \
            -e DJANGO_SECRET_KEY=secret \
            -e DJANGO_DEBUG=True \
            -e DJANGO_ALLOWED_HOSTS=localhost \
            ${{ vars.DOCKER_REGISTRY }}/backend/panel:latest \
            python manage.py test

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-panel
          path: /tmp
      - name: Load Docker image
        run: docker load -i /tmp/backend-panel.tar
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push to the registry
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/backend/panel:latest
          docker push ${{ vars.DOCKER_REGISTRY }}/backend/panel:${{ github.ref_name }}-latest
          docker push ${{ vars.DOCKER_REGISTRY }}/backend/panel:${{ github.ref_name }}-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: push
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}  
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ vars.manifests_repository }}
          ref: ${{ vars.manifests_branch }}
          token: ${{ secrets.manifests_repository_token }}
      - name: Install yq if needed
        run: |
          if ! command -v yq &> /dev/null
          then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod a+x /usr/local/bin/yq
          fi
      - name: Cache ArgocdCLI
        id: cache-argocd-cli
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/argocd
          key: ${{ vars.argocd_server }}-argocd
      - name: Install argocd
        if: steps.cache-argocd-cli.outputs.cache-hit != 'true'
        env:
          ARGOCD_SERVER: ${{ vars.argocd_server }}
        run: |
          curl -sSL -o /usr/local/bin/argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: Update image in the manifests
        run: |
          yq -i '${{ vars.manifests_image_name_path }} = "${{ vars.DOCKER_REGISTRY }}/backend/panel"' ${{ vars.manifests_values_path }}
          yq -i '${{ vars.manifests_image_tag_path }} = "${{ github.ref_name }}-${{ github.sha }}"' ${{ vars.manifests_values_path }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@neor.pro"
          git add ${{ vars.manifests_values_path }}
          git commit -m "Update image to ${{ vars.DOCKER_REGISTRY }}/backend/panel:${{ github.ref_name }}-${{ github.sha }}" 
          git push
      - name: Sync application
        env:
          ARGOCD_SERVER: ${{ vars.argocd_server }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.argocd_auth_token }}
        run: |
          argocd app sync ${{ vars.argocd_app_name }} --async
      - name: Output application url
        env:
          ARGOCD_SERVER: ${{ vars.argocd_server }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.argocd_auth_token }}
        id: deploy
        run: |
          url=$(argocd app get ${{ vars.argocd_app_name }} -o yaml | yq '.status.summary.externalURLs.0')
          echo ::set-output name=webapp-url::${url}
