name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: ""
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: Exchange
        load: true
        tags: "backend/panel:latest,backend/panel:${{ github.ref_name }}-latest,backend/panel:${{ github.ref_name }}-${{ github.sha }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Run tests
        run: |
          docker run --rm \
            -e DATABASE_HOST=postgres \
            -e DATABASE_PORT=5432 \
            -e DATABASE_NAME=testdb \
            -e DATABASE_USER=postgres \
            -e DATABASE_PASSWORD=postgres \
            -e DJANGO_SECRET_KEY=secret \
            -e DJANGO_DEBUG=True \
            -e DJANGO_ALLOWED_HOSTS=localhost \
            backend/panel:latest \
            python manage.py test

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push to the registry
        uses: docker/build-push-action@v5.0.0
        with:
          context: Exchange
          push: true
          tags: "backend/panel:latest,backend/panel:${{ github.ref_name }}-latest,backend/panel:${{ github.ref_name }}-${{ github.sha }}"
